### PR TITLE
Refactor file structure

### PR DESCRIPTION
**Pull request by andrewctam**
- Make peernode a lib
- Move cli out of peernode
- Move server out of peernode
   - Move jobs.rs to server
   - Move files.rs to peernode under peernode::store
   - Move jobs state from the previous config to another field in ServerState

### CODE REVIEW

**Comment by andrewctam** [comment]
@xiej2520 refactored the structure as documented in the PR comment above. Might have messed up everything so make sure it runs as before lol

**Comment by xiej2520** [comment]
```toml
[features]
test_local_markete = []
```
needs to be present in `peernode/Cargo.toml` (and it only needs to be in that one) since peernode is the only crate that interacts with the market. Otherwise looks fine.

**Comment by andrewctam** [comment]
@xiej2520 should we merge this now or later down the line (such as after #27) in case it makes a lot of merge conflicts?

**Comment by xiej2520** [comment]
We can merge it now, I'll try to include this as well as the new Kad market in the next PR.

**Pull request merged**
